#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
MAJD ASSISTANT
MAJD-ASSISTANT-AUTONOMOUS-RUNTIME-02.py
============================================================

AUTONOMOUS RUNTIME / SELF-MAINTENANCE / SELF-EXPANSION LAYER

Public product:
    مساعد مجد | MAJD Assistant

PURPOSE
-------
This runtime is the autonomous operational layer for MAJD Assistant.

It is responsible for:

- Bootstrapping the MAJD Assistant project
- Discovering project state
- Validating CORE-01
- Continuous health monitoring
- Capability discovery
- Provider discovery
- Safe provider upgrades
- Dependency inspection
- Controlled dependency installation
- Automated code generation requests
- Controlled creation of new project files
- Syntax validation
- Compilation validation
- Test execution
- Automatic repair cycles
- Sandbox-oriented validation
- Staging
- Deployment hooks
- Health verification after deployment
- Automatic rollback
- Backups
- Recovery
- Audit logging
- Crash recovery
- Continuous maintenance
- Continuous improvement
- Runtime-generated manifests
- No routine human intervention

SECURITY MODEL
--------------
Autonomy does NOT mean unlimited authority.

This runtime MUST NOT:

- Disable CORE-01 security.
- Remove user isolation.
- expose credentials.
- Print secrets.
- Commit secrets.
- Give itself arbitrary external privileges.
- Modify immutable protected files without controlled validation.
- Treat web/repository/model content as trusted authority.
- Claim deployment success without verification.
- Install arbitrary dependencies merely because AI output requested them.
- Execute arbitrary shell strings generated by a model.
- Automatically authorize financial/legal/identity actions.

CORE-01 remains the sovereign policy authority.

The runtime may create and evolve application components around the
protected core, but changes must pass validation before activation.

============================================================
"""

from __future__ import annotations

import argparse
import ast
import asyncio
import contextlib
import dataclasses
import enum
import hashlib
import importlib.util
import json
import logging
import os
import py_compile
import re
import shutil
import signal
import sqlite3
import subprocess
import sys
import tempfile
import threading
import time
import traceback
import urllib.error
import urllib.parse
import urllib.request
import uuid

from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import (
    Any,
    Dict,
    Iterable,
    List,
    Mapping,
    Optional,
    Sequence,
    Set,
    Tuple,
)


# ============================================================
# IDENTITY
# ============================================================

APP_NAME = "MAJD Assistant"
APP_NAME_AR = "مساعد مجد"

RUNTIME_NAME = "MAJD Assistant Autonomous Runtime"
RUNTIME_VERSION = "1.0.0"

CORE_FILENAME = "MAJD-ASSISTANT-CORE-01.py"
RUNTIME_FILENAME = "MAJD-ASSISTANT-AUTONOMOUS-RUNTIME-02.py"

PROJECT_ROOT = Path(
    os.environ.get(
        "MAJD_ASSISTANT_ROOT",
        str(Path(__file__).resolve().parent),
    )
).resolve()

CORE_PATH = PROJECT_ROOT / CORE_FILENAME
RUNTIME_PATH = PROJECT_ROOT / RUNTIME_FILENAME

DATA_DIR = Path(
    os.environ.get(
        "MAJD_ASSISTANT_DATA_DIR",
        str(PROJECT_ROOT / "data"),
    )
).resolve()

LOG_DIR = Path(
    os.environ.get(
        "MAJD_ASSISTANT_LOG_DIR",
        str(PROJECT_ROOT / "logs"),
    )
).resolve()

STATE_DIR = Path(
    os.environ.get(
        "MAJD_ASSISTANT_STATE_DIR",
        str(PROJECT_ROOT / ".majd-runtime"),
    )
).resolve()

BACKUP_DIR = STATE_DIR / "backups"
STAGING_DIR = STATE_DIR / "staging"
GENERATED_DIR = PROJECT_ROOT / "majd_generated"
TEST_DIR = PROJECT_ROOT / "tests"

RUNTIME_DB = STATE_DIR / "runtime.sqlite3"

MANIFEST_PATH = STATE_DIR / "runtime-manifest.json"
CAPABILITY_PATH = STATE_DIR / "capabilities.json"
HEALTH_PATH = STATE_DIR / "health.json"

HEARTBEAT_SECONDS = max(
    15,
    int(os.environ.get("MAJD_RUNTIME_HEARTBEAT", "60")),
)

MAINTENANCE_SECONDS = max(
    60,
    int(os.environ.get("MAJD_RUNTIME_MAINTENANCE", "900")),
)

MAX_REPAIR_ATTEMPTS = max(
    1,
    min(
        10,
        int(os.environ.get("MAJD_MAX_REPAIR_ATTEMPTS", "3")),
    ),
)

COMMAND_TIMEOUT = max(
    5,
    int(os.environ.get("MAJD_COMMAND_TIMEOUT", "180")),
)

MAX_GENERATED_FILE_BYTES = max(
    4096,
    int(
        os.environ.get(
            "MAJD_MAX_GENERATED_FILE_BYTES",
            "2000000",
        )
    ),
)

AUTO_INSTALL_DEPENDENCIES = (
    os.environ.get(
        "MAJD_AUTO_INSTALL_DEPENDENCIES",
        "0",
    ).strip().lower()
    in {"1", "true", "yes", "on"}
)

AUTO_GIT_COMMIT = (
    os.environ.get(
        "MAJD_AUTO_GIT_COMMIT",
        "0",
    ).strip().lower()
    in {"1", "true", "yes", "on"}
)

AUTO_DEPLOY = (
    os.environ.get(
        "MAJD_AUTO_DEPLOY",
        "0",
    ).strip().lower()
    in {"1", "true", "yes", "on"}
)

ALLOW_CORE_UPDATES = (
    os.environ.get(
        "MAJD_ALLOW_CORE_UPDATES",
        "0",
    ).strip().lower()
    in {"1", "true", "yes", "on"}
)

STOP_EVENT = threading.Event()


# ============================================================
# DIRECTORIES / LOGGING
# ============================================================

for directory in (
    DATA_DIR,
    LOG_DIR,
    STATE_DIR,
    BACKUP_DIR,
    STAGING_DIR,
    GENERATED_DIR,
    TEST_DIR,
):
    directory.mkdir(parents=True, exist_ok=True)

logging.basicConfig(
    level=os.environ.get(
        "MAJD_RUNTIME_LOG_LEVEL",
        "INFO",
    ).upper(),
    format=(
        "%(asctime)s | %(levelname)s | "
        "%(name)s | %(message)s"
    ),
    handlers=[
        logging.StreamHandler(),
        logging.FileHandler(
            LOG_DIR / "majd-assistant-runtime.log",
            encoding="utf-8",
        ),
    ],
)

logger = logging.getLogger("majd.assistant.runtime")


# ============================================================
# UTILITIES
# ============================================================

def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def new_id(prefix: str) -> str:
    return f"{prefix}_{uuid.uuid4().hex}"


def sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()

    with path.open("rb") as handle:
        while True:
            block = handle.read(1024 * 1024)

            if not block:
                break

            digest.update(block)

    return digest.hexdigest()


def safe_json(value: Any) -> str:
    return json.dumps(
        value,
        ensure_ascii=False,
        separators=(",", ":"),
        default=str,
    )


def atomic_write_text(
    path: Path,
    content: str,
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)

    fd, temp_name = tempfile.mkstemp(
        prefix=f".{path.name}.",
        dir=str(path.parent),
    )

    temp_path = Path(temp_name)

    try:
        with os.fdopen(
            fd,
            "w",
            encoding="utf-8",
        ) as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())

        os.replace(temp_path, path)

    finally:
        with contextlib.suppress(FileNotFoundError):
            temp_path.unlink()


def load_json(
    path: Path,
    default: Any,
) -> Any:
    if not path.exists():
        return default

    try:
        return json.loads(
            path.read_text(encoding="utf-8")
        )
    except Exception:
        return default


def write_json(
    path: Path,
    value: Any,
) -> None:
    atomic_write_text(
        path,
        json.dumps(
            value,
            ensure_ascii=False,
            indent=2,
            default=str,
        )
        + "\n",
    )


def relative_path(path: Path) -> str:
    try:
        return str(
            path.resolve().relative_to(
                PROJECT_ROOT.resolve()
            )
        )
    except Exception:
        return str(path.resolve())


# ============================================================
# SECRET PROTECTION
# ============================================================

SECRET_PATTERNS: Tuple[re.Pattern[str], ...] = (
    re.compile(
        r"(?i)\b("
        r"api[_-]?key|secret|token|password|passwd|"
        r"authorization"
        r")\s*[:=]\s*['\"]?([^\s'\";,]+)"
    ),
    re.compile(
        r"\bgh[pousr]_[A-Za-z0-9_]{20,}\b"
    ),
    re.compile(
        r"\bgithub_pat_[A-Za-z0-9_]{20,}\b"
    ),
    re.compile(
        r"\bsk-[A-Za-z0-9_-]{16,}\b"
    ),
    re.compile(
        r"-----BEGIN "
        r"(?:RSA |EC |OPENSSH )?"
        r"PRIVATE KEY-----[\s\S]*?"
        r"-----END "
        r"(?:RSA |EC |OPENSSH )?"
        r"PRIVATE KEY-----"
    ),
)


class SecretGuard:
    @staticmethod
    def redact(value: str) -> str:
        output = value or ""

        for pattern in SECRET_PATTERNS:
            if pattern.groups >= 2:
                output = pattern.sub(
                    lambda match: (
                        f"{match.group(1)}=[REDACTED]"
                    ),
                    output,
                )
            else:
                output = pattern.sub(
                    "[REDACTED_SECRET]",
                    output,
                )

        return output

    @staticmethod
    def contains_secret(value: str) -> bool:
        return any(
            pattern.search(value or "")
            for pattern in SECRET_PATTERNS
        )


# ============================================================
# ENUMS
# ============================================================

class Risk(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class JobStatus(str, enum.Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    PASSED = "PASSED"
    FAILED = "FAILED"
    ROLLED_BACK = "ROLLED_BACK"
    BLOCKED = "BLOCKED"


class ChangeType(str, enum.Enum):
    CREATE = "CREATE"
    UPDATE = "UPDATE"
    DELETE = "DELETE"
    PROVIDER_UPDATE = "PROVIDER_UPDATE"
    DEPENDENCY_UPDATE = "DEPENDENCY_UPDATE"


# ============================================================
# DATA MODELS
# ============================================================

@dataclass
class CommandResult:
    success: bool
    argv: List[str]
    returncode: Optional[int]
    stdout: str = ""
    stderr: str = ""
    timed_out: bool = False
    duration_ms: int = 0


@dataclass
class ValidationResult:
    success: bool
    checks: Dict[str, Any] = field(
        default_factory=dict
    )
    errors: List[str] = field(
        default_factory=list
    )
    warnings: List[str] = field(
        default_factory=list
    )


@dataclass
class ChangeProposal:
    proposal_id: str
    change_type: ChangeType
    relative_path: str
    content: Optional[str]
    reason: str
    source: str
    created_at: str = field(
        default_factory=utc_now
    )


@dataclass
class BackupRecord:
    backup_id: str
    source_path: str
    backup_path: str
    sha256: str
    created_at: str


@dataclass
class ProviderCandidate:
    component: str
    current_version: str
    candidate_version: str
    source: str
    security_score: float
    quality_score: float
    compatibility_score: float
    tests_passed: bool
    sandbox_verified: bool


# ============================================================
# RUNTIME DATABASE
# ============================================================

class RuntimeDatabase:
    def __init__(self, path: Path):
        self.path = path
        self._lock = threading.RLock()
        self.initialize()

    def connect(self) -> sqlite3.Connection:
        connection = sqlite3.connect(
            self.path,
            timeout=30,
            isolation_level=None,
            check_same_thread=False,
        )

        connection.row_factory = sqlite3.Row
        connection.execute(
            "PRAGMA journal_mode=WAL"
        )
        connection.execute(
            "PRAGMA foreign_keys=ON"
        )
        connection.execute(
            "PRAGMA busy_timeout=30000"
        )

        return connection

    def initialize(self) -> None:
        with self._lock, self.connect() as db:
            db.executescript(
                """
                CREATE TABLE IF NOT EXISTS runtime_events (
                    id TEXT PRIMARY KEY,
                    event_type TEXT NOT NULL,
                    risk TEXT NOT NULL,
                    details TEXT NOT NULL,
                    created_at TEXT NOT NULL
                );

                CREATE TABLE IF NOT EXISTS jobs (
                    id TEXT PRIMARY KEY,
                    job_type TEXT NOT NULL,
                    status TEXT NOT NULL,
                    details TEXT NOT NULL,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL
                );

                CREATE TABLE IF NOT EXISTS backups (
                    id TEXT PRIMARY KEY,
                    source_path TEXT NOT NULL,
                    backup_path TEXT NOT NULL,
                    sha256 TEXT NOT NULL,
                    created_at TEXT NOT NULL
                );

                CREATE TABLE IF NOT EXISTS component_versions (
                    component TEXT PRIMARY KEY,
                    version TEXT NOT NULL,
                    source TEXT,
                    metadata TEXT NOT NULL DEFAULT '{}',
                    updated_at TEXT NOT NULL
                );

                CREATE TABLE IF NOT EXISTS generated_files (
                    path TEXT PRIMARY KEY,
                    sha256 TEXT NOT NULL,
                    source TEXT NOT NULL,
                    status TEXT NOT NULL,
                    metadata TEXT NOT NULL DEFAULT '{}',
                    updated_at TEXT NOT NULL
                );
                """
            )

    def event(
        self,
        event_type: str,
        risk: Risk,
        details: Mapping[str, Any],
    ) -> None:
        protected = SecretGuard.redact(
            safe_json(dict(details))
        )

        with self._lock, self.connect() as db:
            db.execute(
                """
                INSERT INTO runtime_events
                (id,event_type,risk,details,created_at)
                VALUES (?,?,?,?,?)
                """,
                (
                    new_id("event"),
                    event_type,
                    risk.value,
                    protected,
                    utc_now(),
                ),
            )

    def create_job(
        self,
        job_type: str,
        details: Mapping[str, Any],
    ) -> str:
        job_id = new_id("job")
        now = utc_now()

        with self._lock, self.connect() as db:
            db.execute(
                """
                INSERT INTO jobs
                (id,job_type,status,details,created_at,updated_at)
                VALUES (?,?,?,?,?,?)
                """,
                (
                    job_id,
                    job_type,
                    JobStatus.PENDING.value,
                    SecretGuard.redact(
                        safe_json(dict(details))
                    ),
                    now,
                    now,
                ),
            )

        return job_id

    def update_job(
        self,
        job_id: str,
        status: JobStatus,
        details: Mapping[str, Any],
    ) -> None:
        with self._lock, self.connect() as db:
            db.execute(
                """
                UPDATE jobs
                SET status = ?,
                    details = ?,
                    updated_at = ?
                WHERE id = ?
                """,
                (
                    status.value,
                    SecretGuard.redact(
                        safe_json(dict(details))
                    ),
                    utc_now(),
                    job_id,
                ),
            )

    def save_backup(
        self,
        record: BackupRecord,
    ) -> None:
        with self._lock, self.connect() as db:
            db.execute(
                """
                INSERT INTO backups
                (id,source_path,backup_path,sha256,created_at)
                VALUES (?,?,?,?,?)
                """,
                (
                    record.backup_id,
                    record.source_path,
                    record.backup_path,
                    record.sha256,
                    record.created_at,
                ),
            )

    def record_generated_file(
        self,
        path: Path,
        source: str,
        status: str,
        metadata: Mapping[str, Any],
    ) -> None:
        digest = (
            sha256_file(path)
            if path.exists()
            else ""
        )

        with self._lock, self.connect() as db:
            db.execute(
                """
                INSERT INTO generated_files
                (path,sha256,source,status,metadata,updated_at)
                VALUES (?,?,?,?,?,?)
                ON CONFLICT(path) DO UPDATE SET
                    sha256=excluded.sha256,
                    source=excluded.source,
                    status=excluded.status,
                    metadata=excluded.metadata,
                    updated_at=excluded.updated_at
                """,
                (
                    relative_path(path),
                    digest,
                    source,
                    status,
                    SecretGuard.redact(
                        safe_json(dict(metadata))
                    ),
                    utc_now(),
                ),
            )


# ============================================================
# COMMAND RUNNER
# ============================================================

class CommandRunner:
    """
    Executes pre-constructed argv arrays only.

    shell=True is intentionally never used.
    """

    def __init__(
        self,
        timeout: int = COMMAND_TIMEOUT,
    ):
        self.timeout = timeout

    def run(
        self,
        argv: Sequence[str],
        cwd: Optional[Path] = None,
        env: Optional[Mapping[str, str]] = None,
        timeout: Optional[int] = None,
    ) -> CommandResult:
        if not argv:
            return CommandResult(
                success=False,
                argv=[],
                returncode=None,
                stderr="EMPTY_COMMAND",
            )

        safe_argv = [str(item) for item in argv]
        started = time.monotonic()

        try:
            process = subprocess.run(
                safe_argv,
                cwd=str(cwd or PROJECT_ROOT),
                env=dict(env) if env else None,
                capture_output=True,
                text=True,
                timeout=timeout or self.timeout,
                shell=False,
                check=False,
            )

            stdout = SecretGuard.redact(
                process.stdout or ""
            )

            stderr = SecretGuard.redact(
                process.stderr or ""
            )

            return CommandResult(
                success=process.returncode == 0,
                argv=safe_argv,
                returncode=process.returncode,
                stdout=stdout,
                stderr=stderr,
                duration_ms=int(
                    (time.monotonic() - started)
                    * 1000
                ),
            )

        except subprocess.TimeoutExpired as exc:
            return CommandResult(
                success=False,
                argv=safe_argv,
                returncode=None,
                stdout=SecretGuard.redact(
                    exc.stdout or ""
                    if isinstance(exc.stdout, str)
                    else ""
                ),
                stderr=SecretGuard.redact(
                    exc.stderr or ""
                    if isinstance(exc.stderr, str)
                    else ""
                ),
                timed_out=True,
                duration_ms=int(
                    (time.monotonic() - started)
                    * 1000
                ),
            )

        except Exception as exc:
            return CommandResult(
                success=False,
                argv=safe_argv,
                returncode=None,
                stderr=SecretGuard.redact(
                    f"{type(exc).__name__}: {exc}"
                ),
                duration_ms=int(
                    (time.monotonic() - started)
                    * 1000
                ),
            )


# ============================================================
# CORE LOADER
# ============================================================

class CoreLoader:
    def __init__(self, path: Path):
        self.path = path
        self.module: Optional[Any] = None

    def validate_exists(self) -> None:
        if not self.path.exists():
            raise FileNotFoundError(
                f"Required core missing: {self.path}"
            )

    def load(self) -> Any:
        self.validate_exists()

        module_name = (
            "majd_assistant_core_01"
        )

        spec = importlib.util.spec_from_file_location(
            module_name,
            self.path,
        )

        if spec is None or spec.loader is None:
            raise RuntimeError(
                "Unable to create CORE-01 module spec"
            )

        module = importlib.util.module_from_spec(
            spec
        )

        sys.modules[module_name] = module
        spec.loader.exec_module(module)

        self.module = module
        return module

    def constitution_fingerprint(self) -> str:
        module = self.module or self.load()

        constitution = getattr(
            module,
            "SOVEREIGN_CONSTITUTION",
            None,
        )

        if not constitution:
            raise RuntimeError(
                "CORE-01 sovereign constitution missing"
            )

        return sha256_bytes(
            safe_json(list(constitution)).encode(
                "utf-8"
            )
        )

    def self_check(self) -> Dict[str, Any]:
        module = self.module or self.load()

        function = getattr(
            module,
            "startup_self_check",
            None,
        )

        if not callable(function):
            raise RuntimeError(
                "CORE-01 startup_self_check missing"
            )

        result = function()

        if not isinstance(result, dict):
            raise RuntimeError(
                "Invalid CORE-01 self-check result"
            )

        return result


# ============================================================
# PROTECTED PATH POLICY
# ============================================================

class ProtectedPathPolicy:
    ABSOLUTELY_PROTECTED = {
        ".git",
        ".github",
        ".ssh",
    }

    PROTECTED_FILES = {
        CORE_FILENAME,
        RUNTIME_FILENAME,
    }

    SECRET_FILE_NAMES = {
        ".env",
        ".env.local",
        ".env.production",
        "credentials.json",
        "secrets.json",
        "id_rsa",
        "id_ed25519",
    }

    @classmethod
    def safe_target(
        cls,
        relative: str,
        allow_core_update: bool = False,
    ) -> Tuple[bool, str]:
        candidate = Path(relative)

        if candidate.is_absolute():
            return False, "ABSOLUTE_PATH_BLOCKED"

        if ".." in candidate.parts:
            return False, "PATH_TRAVERSAL_BLOCKED"

        if not candidate.parts:
            return False, "EMPTY_PATH"

        if candidate.parts[0] in cls.ABSOLUTELY_PROTECTED:
            return False, "PROTECTED_DIRECTORY"

        if candidate.name in cls.SECRET_FILE_NAMES:
            return False, "SECRET_FILE_BLOCKED"

        if candidate.name == RUNTIME_FILENAME:
            return False, "RUNTIME_SELF_MODIFICATION_BLOCKED"

        if (
            candidate.name == CORE_FILENAME
            and not allow_core_update
        ):
            return False, "CORE_UPDATE_BLOCKED"

        return True, "ALLOWED"


# ============================================================
# BACKUP / ROLLBACK
# ============================================================

class BackupManager:
    def __init__(
        self,
        db: RuntimeDatabase,
    ):
        self.db = db

    def backup(
        self,
        path: Path,
    ) -> Optional[BackupRecord]:
        if not path.exists():
            return None

        backup_id = new_id("backup")

        destination = (
            BACKUP_DIR
            / backup_id
            / relative_path(path)
        )

        destination.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        shutil.copy2(
            path,
            destination,
        )

        record = BackupRecord(
            backup_id=backup_id,
            source_path=str(path),
            backup_path=str(destination),
            sha256=sha256_file(destination),
            created_at=utc_now(),
        )

        self.db.save_backup(record)

        return record

    def restore(
        self,
        record: BackupRecord,
    ) -> bool:
        source = Path(record.backup_path)
        destination = Path(record.source_path)

        if not source.exists():
            return False

        if sha256_file(source) != record.sha256:
            return False

        destination.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        shutil.copy2(
            source,
            destination,
        )

        return (
            destination.exists()
            and sha256_file(destination)
            == record.sha256
        )


# ============================================================
# SOURCE VALIDATION
# ============================================================

class SourceValidator:
    FORBIDDEN_PYTHON_CALLS = {
        "eval",
        "exec",
        "compile",
    }

    DANGEROUS_IMPORTS = {
        "pty",
    }

    @classmethod
    def validate_python_source(
        cls,
        content: str,
    ) -> ValidationResult:
        checks: Dict[str, Any] = {}
        errors: List[str] = []
        warnings: List[str] = []

        if len(
            content.encode("utf-8")
        ) > MAX_GENERATED_FILE_BYTES:
            errors.append(
                "GENERATED_FILE_TOO_LARGE"
            )

        if SecretGuard.contains_secret(content):
            errors.append(
                "POSSIBLE_SECRET_IN_SOURCE"
            )

        try:
            tree = ast.parse(content)
            checks["ast_parse"] = True
        except SyntaxError as exc:
            checks["ast_parse"] = False
            errors.append(
                f"SYNTAX_ERROR:{exc.lineno}:{exc.msg}"
            )
            return ValidationResult(
                success=False,
                checks=checks,
                errors=errors,
                warnings=warnings,
            )

        for node in ast.walk(tree):
            if isinstance(node, ast.Call):
                if isinstance(node.func, ast.Name):
                    if (
                        node.func.id
                        in cls.FORBIDDEN_PYTHON_CALLS
                    ):
                        warnings.append(
                            f"REVIEW_CALL:{node.func.id}"
                        )

            if isinstance(node, ast.Import):
                for alias in node.names:
                    if (
                        alias.name.split(".")[0]
                        in cls.DANGEROUS_IMPORTS
                    ):
                        warnings.append(
                            f"REVIEW_IMPORT:{alias.name}"
                        )

            if isinstance(
                node,
                ast.ImportFrom,
            ):
                if (
                    node.module
                    and node.module.split(".")[0]
                    in cls.DANGEROUS_IMPORTS
                ):
                    warnings.append(
                        f"REVIEW_IMPORT:{node.module}"
                    )

        checks["secret_scan"] = (
            "POSSIBLE_SECRET_IN_SOURCE"
            not in errors
        )

        return ValidationResult(
            success=not errors,
            checks=checks,
            errors=errors,
            warnings=warnings,
        )


# ============================================================
# PROJECT VALIDATOR
# ============================================================

class ProjectValidator:
    def __init__(
        self,
        runner: CommandRunner,
    ):
        self.runner = runner

    def compile_file(
        self,
        path: Path,
    ) -> ValidationResult:
        result = self.runner.run(
            [
                sys.executable,
                "-m",
                "py_compile",
                str(path),
            ],
            cwd=PROJECT_ROOT,
        )

        return ValidationResult(
            success=result.success,
            checks={
                "py_compile": result.success,
                "returncode": result.returncode,
            },
            errors=(
                []
                if result.success
                else [result.stderr or result.stdout]
            ),
        )

    def compile_project(
        self,
    ) -> ValidationResult:
        python_files = [
            path
            for path in PROJECT_ROOT.rglob("*.py")
            if ".git" not in path.parts
            and "__pycache__" not in path.parts
            and ".majd-runtime" not in path.parts
        ]

        errors: List[str] = []
        compiled = 0

        for path in python_files:
            result = self.compile_file(path)

            if result.success:
                compiled += 1
            else:
                errors.extend(
                    [
                        f"{relative_path(path)}: {error}"
                        for error in result.errors
                    ]
                )

        return ValidationResult(
            success=not errors,
            checks={
                "python_files": len(
                    python_files
                ),
                "compiled": compiled,
            },
            errors=errors,
        )

    def run_core_self_check(
        self,
    ) -> ValidationResult:
        result = self.runner.run(
            [
                sys.executable,
                str(CORE_PATH),
                "--self-check",
            ],
            cwd=PROJECT_ROOT,
        )

        checks: Dict[str, Any] = {
            "command_success": result.success,
        }

        if result.success:
            try:
                payload = json.loads(
                    result.stdout
                )
                checks["core"] = payload

                return ValidationResult(
                    success=bool(
                        payload.get("ok")
                    ),
                    checks=checks,
                    errors=(
                        []
                        if payload.get("ok")
                        else [
                            "CORE_SELF_CHECK_FAILED"
                        ]
                    ),
                )
            except Exception:
                pass

        return ValidationResult(
            success=False,
            checks=checks,
            errors=[
                result.stderr
                or result.stdout
                or "CORE_SELF_CHECK_FAILED"
            ],
        )

    def run_tests(
        self,
    ) -> ValidationResult:
        test_files = list(
            TEST_DIR.glob("test_*.py")
        )

        if not test_files:
            return ValidationResult(
                success=True,
                checks={
                    "tests_present": False,
                    "tests_run": 0,
                },
                warnings=[
                    "NO_TEST_FILES_PRESENT"
                ],
            )

        result = self.runner.run(
            [
                sys.executable,
                "-m",
                "unittest",
                "discover",
                "-s",
                str(TEST_DIR),
                "-p",
                "test_*.py",
            ],
            cwd=PROJECT_ROOT,
            timeout=COMMAND_TIMEOUT,
        )

        return ValidationResult(
            success=result.success,
            checks={
                "tests_present": True,
                "command_success": (
                    result.success
                ),
            },
            errors=(
                []
                if result.success
                else [
                    result.stderr
                    or result.stdout
                ]
            ),
        )

    def full_validation(
        self,
    ) -> ValidationResult:
        compile_result = (
            self.compile_project()
        )

        core_result = (
            self.run_core_self_check()
        )

        tests_result = self.run_tests()

        success = (
            compile_result.success
            and core_result.success
            and tests_result.success
        )

        return ValidationResult(
            success=success,
            checks={
                "compile": (
                    compile_result.checks
                ),
                "core": core_result.checks,
                "tests": tests_result.checks,
            },
            errors=(
                compile_result.errors
                + core_result.errors
                + tests_result.errors
            ),
            warnings=(
                compile_result.warnings
                + core_result.warnings
                + tests_result.warnings
            ),
        )


# ============================================================
# DEPENDENCY POLICY
# ============================================================

class DependencyManager:
    """
    Dependency installation is restricted.

    Runtime may only install packages declared in the project's
    requirements file, not arbitrary model-generated package names.
    """

    REQUIREMENTS_FILE = (
        PROJECT_ROOT / "requirements.txt"
    )

    PACKAGE_RE = re.compile(
        r"^[A-Za-z0-9_.-]+"
        r"(?:\[[A-Za-z0-9_,.-]+\])?"
        r"(?:==|>=|<=|~=|>|<)?"
        r"[A-Za-z0-9_.+-]*$"
    )

    def __init__(
        self,
        runner: CommandRunner,
        db: RuntimeDatabase,
    ):
        self.runner = runner
        self.db = db

    def declared_packages(self) -> List[str]:
        if not self.REQUIREMENTS_FILE.exists():
            return []

        packages: List[str] = []

        for raw in self.REQUIREMENTS_FILE.read_text(
            encoding="utf-8"
        ).splitlines():
            line = raw.strip()

            if not line or line.startswith("#"):
                continue

            if (
                line.startswith("-")
                or "://" in line
                or line.startswith("git+")
            ):
                self.db.event(
                    "DEPENDENCY_BLOCKED",
                    Risk.HIGH,
                    {"entry": line},
                )
                continue

            if not self.PACKAGE_RE.fullmatch(
                line
            ):
                self.db.event(
                    "DEPENDENCY_BLOCKED",
                    Risk.HIGH,
                    {"entry": line},
                )
                continue

            packages.append(line)

        return packages

    def install_declared(
        self,
    ) -> CommandResult:
        packages = self.declared_packages()

        if not packages:
            return CommandResult(
                success=True,
                argv=[],
                returncode=0,
                stdout="No declared dependencies.",
            )

        if not AUTO_INSTALL_DEPENDENCIES:
            return CommandResult(
                success=False,
                argv=[],
                returncode=None,
                stderr=(
                    "Automatic dependency installation "
                    "is disabled."
                ),
            )

        argv = [
            sys.executable,
            "-m",
            "pip",
            "install",
            "--disable-pip-version-check",
            "--no-input",
            *packages,
        ]

        result = self.runner.run(
            argv,
            cwd=PROJECT_ROOT,
            timeout=max(
                COMMAND_TIMEOUT,
                600,
            ),
        )

        self.db.event(
            "DEPENDENCY_INSTALL",
            (
                Risk.MEDIUM
                if result.success
                else Risk.HIGH
            ),
            {
                "success": result.success,
                "packages": packages,
                "returncode": (
                    result.returncode
                ),
            },
        )

        return result


# ============================================================
# AI DEVELOPMENT GATEWAY
# ============================================================

class DevelopmentGateway:
    """
    Talks to a MAJD-compatible development gateway.

    Environment:
        MAJD_DEVELOPMENT_GATEWAY_URL
        MAJD_DEVELOPMENT_GATEWAY_TOKEN

    Expected:
        GET  /health
        POST /v1/develop

    The gateway proposes source code.
    This runtime does not blindly trust it.
    """

    def __init__(self):
        self.base_url = os.environ.get(
            "MAJD_DEVELOPMENT_GATEWAY_URL",
            "",
        ).rstrip("/")

        self.token = os.environ.get(
            "MAJD_DEVELOPMENT_GATEWAY_TOKEN",
            "",
        )

    @property
    def configured(self) -> bool:
        return bool(self.base_url)

    def _headers(self) -> Dict[str, str]:
        headers = {
            "Content-Type": "application/json",
            "User-Agent": (
                f"MAJD-Autonomous-Runtime/"
                f"{RUNTIME_VERSION}"
            ),
        }

        if self.token:
            headers["Authorization"] = (
                f"Bearer {self.token}"
            )

        return headers

    def _json_request(
        self,
        method: str,
        endpoint: str,
        payload: Optional[
            Dict[str, Any]
        ] = None,
    ) -> Dict[str, Any]:
        url = (
            f"{self.base_url}"
            f"{endpoint}"
        )

        data = (
            safe_json(payload).encode(
                "utf-8"
            )
            if payload is not None
            else None
        )

        request = urllib.request.Request(
            url=url,
            data=data,
            headers=self._headers(),
            method=method,
        )

        with urllib.request.urlopen(
            request,
            timeout=60,
        ) as response:
            raw = response.read(
                MAX_GENERATED_FILE_BYTES
                + 500000
            )

        if (
            len(raw)
            > MAX_GENERATED_FILE_BYTES
            + 500000
        ):
            raise ValueError(
                "Development response too large"
            )

        return json.loads(
            raw.decode("utf-8")
        )

    def healthy(self) -> bool:
        if not self.configured:
            return False

        try:
            result = self._json_request(
                "GET",
                "/health",
            )
            return bool(
                result.get("ok")
            )
        except Exception:
            return False

    def propose(
        self,
        objective: str,
        project_manifest: Mapping[
            str,
            Any,
        ],
        errors: Sequence[str],
        allowed_root: str = "majd_generated",
    ) -> Optional[ChangeProposal]:
        if not self.healthy():
            return None

        response = self._json_request(
            "POST",
            "/v1/develop",
            {
                "objective": objective,
                "project_manifest": (
                    dict(project_manifest)
                ),
                "errors": list(errors),
                "constraints": {
                    "allowed_root": (
                        allowed_root
                    ),
                    "no_secrets": True,
                    "no_shell_strings": True,
                    "no_security_bypass": True,
                    "complete_files_only": True,
                    "production_quality": True,
                },
            },
        )

        if not response.get("success"):
            return None

        relative = str(
            response.get(
                "relative_path",
                "",
            )
        ).strip()

        content = response.get(
            "content"
        )

        if not relative or not isinstance(
            content,
            str,
        ):
            return None

        return ChangeProposal(
            proposal_id=new_id("proposal"),
            change_type=ChangeType.CREATE,
            relative_path=relative,
            content=content,
            reason=str(
                response.get(
                    "reason",
                    objective,
                )
            ),
            source=str(
                response.get(
                    "provider",
                    "development-gateway",
                )
            ),
        )


# ============================================================
# CHANGE MANAGER
# ============================================================

class ChangeManager:
    def __init__(
        self,
        db: RuntimeDatabase,
        backup_manager: BackupManager,
        validator: ProjectValidator,
    ):
        self.db = db
        self.backup_manager = (
            backup_manager
        )
        self.validator = validator

    def _target(
        self,
        relative: str,
    ) -> Path:
        return (
            PROJECT_ROOT / relative
        ).resolve()

    def _inside_project(
        self,
        path: Path,
    ) -> bool:
        try:
            path.relative_to(
                PROJECT_ROOT.resolve()
            )
            return True
        except ValueError:
            return False

    def apply(
        self,
        proposal: ChangeProposal,
    ) -> ValidationResult:
        allowed, reason = (
            ProtectedPathPolicy.safe_target(
                proposal.relative_path,
                allow_core_update=(
                    ALLOW_CORE_UPDATES
                ),
            )
        )

        if not allowed:
            self.db.event(
                "CHANGE_BLOCKED",
                Risk.HIGH,
                {
                    "proposal": (
                        proposal.proposal_id
                    ),
                    "path": (
                        proposal.relative_path
                    ),
                    "reason": reason,
                },
            )

            return ValidationResult(
                success=False,
                errors=[reason],
            )

        target = self._target(
            proposal.relative_path
        )

        if not self._inside_project(
            target
        ):
            return ValidationResult(
                success=False,
                errors=[
                    "TARGET_OUTSIDE_PROJECT"
                ],
            )

        if (
            proposal.change_type
            in {
                ChangeType.CREATE,
                ChangeType.UPDATE,
            }
            and proposal.content is None
        ):
            return ValidationResult(
                success=False,
                errors=[
                    "MISSING_CONTENT"
                ],
            )

        content = proposal.content or ""

        if target.suffix == ".py":
            source_validation = (
                SourceValidator
                .validate_python_source(
                    content
                )
            )

            if not source_validation.success:
                return source_validation

        elif SecretGuard.contains_secret(
            content
        ):
            return ValidationResult(
                success=False,
                errors=[
                    "POSSIBLE_SECRET_IN_SOURCE"
                ],
            )

        backup = (
            self.backup_manager.backup(
                target
            )
        )

        existed_before = target.exists()

        try:
            if proposal.change_type in {
                ChangeType.CREATE,
                ChangeType.UPDATE,
            }:
                atomic_write_text(
                    target,
                    content,
                )

            elif (
                proposal.change_type
                == ChangeType.DELETE
            ):
                if target.exists():
                    target.unlink()

            validation = (
                self.validator.full_validation()
            )

            if validation.success:
                self.db.record_generated_file(
                    target,
                    proposal.source,
                    "ACTIVE",
                    {
                        "proposal_id": (
                            proposal.proposal_id
                        ),
                        "reason": proposal.reason,
                    },
                )

                self.db.event(
                    "CHANGE_ACTIVATED",
                    Risk.MEDIUM,
                    {
                        "proposal": (
                            proposal.proposal_id
                        ),
                        "path": (
                            proposal.relative_path
                        ),
                        "source": (
                            proposal.source
                        ),
                    },
                )

                return validation

            # Automatic rollback.
            if backup is not None:
                restored = (
                    self.backup_manager.restore(
                        backup
                    )
                )
            elif not existed_before:
                with contextlib.suppress(
                    FileNotFoundError
                ):
                    target.unlink()

                restored = not target.exists()
            else:
                restored = False

            self.db.event(
                "CHANGE_ROLLBACK",
                Risk.HIGH,
                {
                    "proposal": (
                        proposal.proposal_id
                    ),
                    "path": (
                        proposal.relative_path
                    ),
                    "restored": restored,
                    "errors": (
                        validation.errors
                    ),
                },
            )

            validation.errors.append(
                "ROLLED_BACK"
                if restored
                else "ROLLBACK_FAILED"
            )

            return validation

        except Exception as exc:
            restored = False

            if backup is not None:
                restored = (
                    self.backup_manager.restore(
                        backup
                    )
                )
            elif not existed_before:
                with contextlib.suppress(
                    FileNotFoundError
                ):
                    target.unlink()
                restored = True

            return ValidationResult(
                success=False,
                errors=[
                    f"{type(exc).__name__}: "
                    f"{exc}",
                    (
                        "ROLLED_BACK"
                        if restored
                        else "ROLLBACK_FAILED"
                    ),
                ],
            )


# ============================================================
# PROVIDER UPDATE POLICY
# ============================================================

class ProviderUpdatePolicy:
    MIN_SECURITY = 0.95
    MIN_QUALITY = 0.85
    MIN_COMPATIBILITY = 0.90

    @classmethod
    def approve(
        cls,
        candidate: ProviderCandidate,
    ) -> Tuple[bool, str]:
        if not candidate.tests_passed:
            return False, "TESTS_FAILED"

        if not candidate.sandbox_verified:
            return False, "SANDBOX_NOT_VERIFIED"

        if (
            candidate.security_score
            < cls.MIN_SECURITY
        ):
            return False, "SECURITY_TOO_LOW"

        if (
            candidate.quality_score
            < cls.MIN_QUALITY
        ):
            return False, "QUALITY_TOO_LOW"

        if (
            candidate.compatibility_score
            < cls.MIN_COMPATIBILITY
        ):
            return (
                False,
                "COMPATIBILITY_TOO_LOW",
            )

        return True, "APPROVED"


# ============================================================
# GIT MANAGER
# ============================================================

class GitManager:
    def __init__(
        self,
        runner: CommandRunner,
        db: RuntimeDatabase,
    ):
        self.runner = runner
        self.db = db

    def available(self) -> bool:
        return (
            shutil.which("git")
            is not None
            and (
                PROJECT_ROOT / ".git"
            ).exists()
        )

    def status(self) -> CommandResult:
        if not self.available():
            return CommandResult(
                success=False,
                argv=[],
                returncode=None,
                stderr="GIT_NOT_AVAILABLE",
            )

        return self.runner.run(
            [
                "git",
                "status",
                "--porcelain",
            ],
            cwd=PROJECT_ROOT,
        )

    def commit_generated_changes(
        self,
        message: str,
    ) -> CommandResult:
        if not AUTO_GIT_COMMIT:
            return CommandResult(
                success=False,
                argv=[],
                returncode=None,
                stderr=(
                    "AUTO_GIT_COMMIT_DISABLED"
                ),
            )

        if not self.available():
            return CommandResult(
                success=False,
                argv=[],
                returncode=None,
                stderr="GIT_NOT_AVAILABLE",
            )

        # Only generated/runtime-owned paths.
        add_result = self.runner.run(
            [
                "git",
                "add",
                "--",
                "majd_generated",
                "tests",
                "requirements.txt",
            ],
            cwd=PROJECT_ROOT,
        )

        if not add_result.success:
            return add_result

        result = self.runner.run(
            [
                "git",
                "commit",
                "-m",
                message,
            ],
            cwd=PROJECT_ROOT,
        )

        self.db.event(
            "GIT_COMMIT",
            (
                Risk.MEDIUM
                if result.success
                else Risk.HIGH
            ),
            {
                "success": result.success,
                "returncode": (
                    result.returncode
                ),
            },
        )

        return result


# ============================================================
# DEPLOYMENT MANAGER
# ============================================================

class DeploymentManager:
    """
    Deployment uses fixed configured hooks.

    No AI-generated shell command is executed.

    Supported environment variables:
        MAJD_DEPLOY_EXECUTABLE
        MAJD_DEPLOY_ARG_1
        ...
        MAJD_DEPLOY_ARG_20

        MAJD_HEALTH_URL
    """

    def __init__(
        self,
        runner: CommandRunner,
        db: RuntimeDatabase,
    ):
        self.runner = runner
        self.db = db

    def deployment_argv(
        self,
    ) -> List[str]:
        executable = os.environ.get(
            "MAJD_DEPLOY_EXECUTABLE",
            "",
        ).strip()

        if not executable:
            return []

        argv = [executable]

        for index in range(1, 21):
            value = os.environ.get(
                f"MAJD_DEPLOY_ARG_{index}"
            )

            if value is None:
                continue

            argv.append(value)

        return argv

    def deploy(self) -> CommandResult:
        if not AUTO_DEPLOY:
            return CommandResult(
                success=False,
                argv=[],
                returncode=None,
                stderr="AUTO_DEPLOY_DISABLED",
            )

        argv = self.deployment_argv()

        if not argv:
            return CommandResult(
                success=False,
                argv=[],
                returncode=None,
                stderr=(
                    "DEPLOYMENT_HOOK_NOT_CONFIGURED"
                ),
            )

        result = self.runner.run(
            argv,
            cwd=PROJECT_ROOT,
            timeout=max(
                COMMAND_TIMEOUT,
                600,
            ),
        )

        self.db.event(
            "DEPLOYMENT_EXECUTED",
            (
                Risk.MEDIUM
                if result.success
                else Risk.HIGH
            ),
            {
                "success": result.success,
                "returncode": (
                    result.returncode
                ),
            },
        )

        return result

    def health_check(self) -> bool:
        url = os.environ.get(
            "MAJD_HEALTH_URL",
            "",
        ).strip()

        if not url:
            return False

        try:
            request = urllib.request.Request(
                url=url,
                method="GET",
                headers={
                    "User-Agent": (
                        f"MAJD-Runtime/"
                        f"{RUNTIME_VERSION}"
                    )
                },
            )

            with urllib.request.urlopen(
                request,
                timeout=20,
            ) as response:
                status = int(
                    getattr(
                        response,
                        "status",
                        0,
                    )
                )

                body = response.read(
                    100000
                )

            if status < 200 or status >= 300:
                return False

            with contextlib.suppress(
                Exception
            ):
                payload = json.loads(
                    body.decode("utf-8")
                )

                if "ok" in payload:
                    return bool(
                        payload["ok"]
                    )

            return True

        except Exception:
            return False


# ============================================================
# PROJECT MANIFEST
# ============================================================

class ProjectManifest:
    @staticmethod
    def build(
        core_loader: CoreLoader,
    ) -> Dict[str, Any]:
        files: List[Dict[str, Any]] = []

        for path in PROJECT_ROOT.rglob("*"):
            if not path.is_file():
                continue

            if ".git" in path.parts:
                continue

            if "__pycache__" in path.parts:
                continue

            if ".majd-runtime" in path.parts:
                continue

            try:
                size = path.stat().st_size
            except OSError:
                continue

            files.append(
                {
                    "path": relative_path(
                        path
                    ),
                    "size": size,
                    "sha256": (
                        sha256_file(path)
                        if size <= 5_000_000
                        else None
                    ),
                }
            )

        return {
            "project": "MAJD-ASSISTANT",
            "public_name": APP_NAME,
            "runtime_version": (
                RUNTIME_VERSION
            ),
            "generated_at": utc_now(),
            "project_root": str(
                PROJECT_ROOT
            ),
            "core": {
                "file": CORE_FILENAME,
                "exists": CORE_PATH.exists(),
                "sha256": (
                    sha256_file(CORE_PATH)
                    if CORE_PATH.exists()
                    else None
                ),
                "constitution_fingerprint": (
                    core_loader
                    .constitution_fingerprint()
                ),
            },
            "runtime": {
                "file": RUNTIME_FILENAME,
                "sha256": (
                    sha256_file(
                        RUNTIME_PATH
                    )
                    if RUNTIME_PATH.exists()
                    else None
                ),
            },
            "files": files,
        }


# ============================================================
# AUTONOMOUS DEVELOPMENT ENGINE
# ============================================================

class AutonomousDeveloper:
    def __init__(
        self,
        db: RuntimeDatabase,
        gateway: DevelopmentGateway,
        changes: ChangeManager,
        validator: ProjectValidator,
        core_loader: CoreLoader,
    ):
        self.db = db
        self.gateway = gateway
        self.changes = changes
        self.validator = validator
        self.core_loader = core_loader

    def develop(
        self,
        objective: str,
    ) -> ValidationResult:
        job_id = self.db.create_job(
            "AUTONOMOUS_DEVELOPMENT",
            {"objective": objective},
        )

        self.db.update_job(
            job_id,
            JobStatus.RUNNING,
            {"objective": objective},
        )

        baseline = (
            self.validator.full_validation()
        )

        errors = list(
            baseline.errors
        )

        for attempt in range(
            1,
            MAX_REPAIR_ATTEMPTS + 1,
        ):
            manifest = (
                ProjectManifest.build(
                    self.core_loader
                )
            )

            proposal = (
                self.gateway.propose(
                    objective=objective,
                    project_manifest=manifest,
                    errors=errors,
                    allowed_root=(
                        "majd_generated"
                    ),
                )
            )

            if proposal is None:
                result = ValidationResult(
                    success=False,
                    errors=[
                        "DEVELOPMENT_GATEWAY_UNAVAILABLE"
                    ],
                )

                self.db.update_job(
                    job_id,
                    JobStatus.BLOCKED,
                    {
                        "attempt": attempt,
                        "errors": (
                            result.errors
                        ),
                    },
                )

                return result

            # Enforce generated component root.
            proposal_path = Path(
                proposal.relative_path
            )

            if (
                not proposal_path.parts
                or proposal_path.parts[0]
                != "majd_generated"
            ):
                result = ValidationResult(
                    success=False,
                    errors=[
                        "AI_PROPOSAL_OUTSIDE_GENERATED_ROOT"
                    ],
                )

                self.db.event(
                    "AI_PROPOSAL_BLOCKED",
                    Risk.HIGH,
                    {
                        "path": (
                            proposal.relative_path
                        )
                    },
                )

                errors = result.errors
                continue

            result = self.changes.apply(
                proposal
            )

            if result.success:
                self.db.update_job(
                    job_id,
                    JobStatus.PASSED,
                    {
                        "attempt": attempt,
                        "proposal": (
                            proposal.proposal_id
                        ),
                        "path": (
                            proposal.relative_path
                        ),
                    },
                )

                return result

            errors = result.errors

        result = ValidationResult(
            success=False,
            errors=errors
            or [
                "MAX_REPAIR_ATTEMPTS_REACHED"
            ],
        )

        self.db.update_job(
            job_id,
            JobStatus.FAILED,
            {
                "errors": result.errors,
                "attempts": (
                    MAX_REPAIR_ATTEMPTS
                ),
            },
        )

        return result


# ============================================================
# CAPABILITY DISCOVERY
# ============================================================

class CapabilityDiscovery:
    GATEWAYS = {
        "ai": "MAJD_AI_GATEWAY_URL",
        "search": (
            "MAJD_SEARCH_GATEWAY_URL"
        ),
        "places": (
            "MAJD_PLACES_GATEWAY_URL"
        ),
        "media": (
            "MAJD_MEDIA_GATEWAY_URL"
        ),
        "voice": (
            "MAJD_VOICE_GATEWAY_URL"
        ),
        "connector": (
            "MAJD_CONNECTOR_GATEWAY_URL"
        ),
        "execution": (
            "MAJD_EXECUTION_GATEWAY_URL"
        ),
        "development": (
            "MAJD_DEVELOPMENT_GATEWAY_URL"
        ),
    }

    @staticmethod
    def discover() -> Dict[str, Any]:
        gateways: Dict[str, Any] = {}

        for name, variable in (
            CapabilityDiscovery
            .GATEWAYS.items()
        ):
            value = os.environ.get(
                variable,
                "",
            ).strip()

            gateways[name] = {
                "configured": bool(value),
                # Never persist secret/token.
                "url_configured": bool(
                    value
                ),
            }

        capabilities = {
            "conversation": True,
            "multilingual": True,
            "coding_contract": True,
            "live_search": bool(
                os.environ.get(
                    "MAJD_SEARCH_GATEWAY_URL"
                )
            ),
            "places": bool(
                os.environ.get(
                    "MAJD_PLACES_GATEWAY_URL"
                )
            ),
            "images": bool(
                os.environ.get(
                    "MAJD_MEDIA_GATEWAY_URL"
                )
            ),
            "animation": bool(
                os.environ.get(
                    "MAJD_MEDIA_GATEWAY_URL"
                )
            ),
            "motion_graphics": bool(
                os.environ.get(
                    "MAJD_MEDIA_GATEWAY_URL"
                )
            ),
            "voice": bool(
                os.environ.get(
                    "MAJD_VOICE_GATEWAY_URL"
                )
            ),
            "repository_connectors": bool(
                os.environ.get(
                    "MAJD_CONNECTOR_GATEWAY_URL"
                )
            ),
            "sandbox_execution": bool(
                os.environ.get(
                    "MAJD_EXECUTION_GATEWAY_URL"
                )
            ),
            "autonomous_development": bool(
                os.environ.get(
                    "MAJD_DEVELOPMENT_GATEWAY_URL"
                )
            ),
        }

        return {
            "time": utc_now(),
            "gateways": gateways,
            "capabilities": capabilities,
        }


# ============================================================
# HEALTH ENGINE
# ============================================================

class HealthEngine:
    def __init__(
        self,
        validator: ProjectValidator,
        core_loader: CoreLoader,
        db: RuntimeDatabase,
    ):
        self.validator = validator
        self.core_loader = core_loader
        self.db = db

    def check(self) -> Dict[str, Any]:
        started = time.monotonic()

        validation = (
            self.validator.full_validation()
        )

        capabilities = (
            CapabilityDiscovery.discover()
        )

        result = {
            "ok": validation.success,
            "time": utc_now(),
            "runtime": {
                "name": RUNTIME_NAME,
                "version": (
                    RUNTIME_VERSION
                ),
            },
            "core": {
                "exists": CORE_PATH.exists(),
                "constitution_fingerprint": (
                    self.core_loader
                    .constitution_fingerprint()
                ),
            },
            "validation": {
                "success": (
                    validation.success
                ),
                "checks": (
                    validation.checks
                ),
                "errors": (
                    validation.errors
                ),
                "warnings": (
                    validation.warnings
                ),
            },
            "capabilities": capabilities,
            "duration_ms": int(
                (
                    time.monotonic()
                    - started
                )
                * 1000
            ),
        }

        write_json(
            HEALTH_PATH,
            result,
        )

        write_json(
            CAPABILITY_PATH,
            capabilities,
        )

        self.db.event(
            "HEALTH_CHECK",
            (
                Risk.LOW
                if result["ok"]
                else Risk.HIGH
            ),
            {
                "ok": result["ok"],
                "duration_ms": (
                    result["duration_ms"]
                ),
                "errors": (
                    validation.errors
                ),
            },
        )

        return result


# ============================================================
# MAINTENANCE ENGINE
# ============================================================

class MaintenanceEngine:
    def __init__(
        self,
        db: RuntimeDatabase,
        health: HealthEngine,
        dependencies: DependencyManager,
        developer: AutonomousDeveloper,
        git: GitManager,
        deployer: DeploymentManager,
        core_loader: CoreLoader,
    ):
        self.db = db
        self.health = health
        self.dependencies = (
            dependencies
        )
        self.developer = developer
        self.git = git
        self.deployer = deployer
        self.core_loader = core_loader

    def maintenance_cycle(
        self,
    ) -> Dict[str, Any]:
        cycle_id = new_id("cycle")
        started = time.monotonic()

        self.db.event(
            "MAINTENANCE_START",
            Risk.LOW,
            {"cycle_id": cycle_id},
        )

        health_before = (
            self.health.check()
        )

        actions: List[
            Dict[str, Any]
        ] = []

        if not health_before["ok"]:
            errors = (
                health_before[
                    "validation"
                ]["errors"]
            )

            objective = (
                "Repair MAJD Assistant project "
                "validation failures without "
                "changing protected security "
                "policy. Current failures: "
                + " | ".join(errors[:20])
            )

            repair = (
                self.developer.develop(
                    objective
                )
            )

            actions.append(
                {
                    "action": (
                        "automatic_repair"
                    ),
                    "success": (
                        repair.success
                    ),
                    "errors": repair.errors,
                }
            )

        health_after = (
            self.health.check()
        )

        if health_after["ok"]:
            continuous_development = (
                self.developer.develop(
                    (
                        "Continue developing MAJD Assistant "
                        "autonomously. Inspect the current "
                        "project manifest and existing generated "
                        "components, determine what is still "
                        "missing or incomplete, and implement "
                        "the next required component under "
                        "majd_generated without changing the "
                        "protected architecture or duplicating "
                        "completed work."
                    )
                )
            )

            actions.append(
                {
                    "action": (
                        "continuous_autonomous_development"
                    ),
                    "success": (
                        continuous_development.success
                    ),
                    "errors": (
                        continuous_development.errors
                    ),
                    "warnings": (
                        continuous_development.warnings
                    ),
                }
            )

            health_after = (
                self.health.check()
            )

        if (
            health_after["ok"]
            and AUTO_GIT_COMMIT
        ):
            git_result = (
                self.git
                .commit_generated_changes(
                    "MAJD autonomous "
                    "validated update"
                )
            )

            actions.append(
                {
                    "action": "git_commit",
                    "success": (
                        git_result.success
                    ),
                    "returncode": (
                        git_result.returncode
                    ),
                }
            )

        deployment_verified = False

        if (
            health_after["ok"]
            and AUTO_DEPLOY
        ):
            deployment = (
                self.deployer.deploy()
            )

            if deployment.success:
                deployment_verified = (
                    self.deployer
                    .health_check()
                )

            actions.append(
                {
                    "action": "deployment",
                    "command_success": (
                        deployment.success
                    ),
                    "health_verified": (
                        deployment_verified
                    ),
                }
            )

            if (
                deployment.success
                and not deployment_verified
            ):
                self.db.event(
                    "DEPLOYMENT_UNVERIFIED",
                    Risk.CRITICAL,
                    {
                        "cycle_id": (
                            cycle_id
                        )
                    },
                )

        result = {
            "cycle_id": cycle_id,
            "ok": health_after["ok"],
            "health_before": (
                health_before["ok"]
            ),
            "health_after": (
                health_after["ok"]
            ),
            "actions": actions,
            "duration_ms": int(
                (
                    time.monotonic()
                    - started
                )
                * 1000
            ),
            "time": utc_now(),
        }

        self.db.event(
            "MAINTENANCE_COMPLETE",
            (
                Risk.LOW
                if result["ok"]
                else Risk.HIGH
            ),
            result,
        )

        return result


# ============================================================
# RUNTIME
# ============================================================

class MajdAutonomousRuntime:
    def __init__(self):
        self.db = RuntimeDatabase(
            RUNTIME_DB
        )

        self.runner = CommandRunner()

        self.core_loader = CoreLoader(
            CORE_PATH
        )

        self.core = (
            self.core_loader.load()
        )

        self.initial_constitution = (
            self.core_loader
            .constitution_fingerprint()
        )

        self.backups = BackupManager(
            self.db
        )

        self.validator = (
            ProjectValidator(
                self.runner
            )
        )

        self.dependencies = (
            DependencyManager(
                self.runner,
                self.db,
            )
        )

        self.gateway = (
            DevelopmentGateway()
        )

        self.changes = ChangeManager(
            self.db,
            self.backups,
            self.validator,
        )

        self.developer = (
            AutonomousDeveloper(
                self.db,
                self.gateway,
                self.changes,
                self.validator,
                self.core_loader,
            )
        )

        self.git = GitManager(
            self.runner,
            self.db,
        )

        self.deployer = (
            DeploymentManager(
                self.runner,
                self.db,
            )
        )

        self.health_engine = (
            HealthEngine(
                self.validator,
                self.core_loader,
                self.db,
            )
        )

        self.maintenance = (
            MaintenanceEngine(
                self.db,
                self.health_engine,
                self.dependencies,
                self.developer,
                self.git,
                self.deployer,
                self.core_loader,
            )
        )

        self._write_manifest()

    def _assert_constitution(
        self,
    ) -> None:
        current = (
            self.core_loader
            .constitution_fingerprint()
        )

        if (
            current
            != self.initial_constitution
        ):
            self.db.event(
                "CONSTITUTION_CHANGED",
                Risk.CRITICAL,
                {
                    "expected": (
                        self.initial_constitution
                    ),
                    "actual": current,
                },
            )

            raise RuntimeError(
                "Sovereign constitution "
                "changed during runtime"
            )

    def _write_manifest(self) -> None:
        manifest = (
            ProjectManifest.build(
                self.core_loader
            )
        )

        write_json(
            MANIFEST_PATH,
            manifest,
        )

    def bootstrap(self) -> Dict[str, Any]:
        logger.info(
            "Bootstrapping %s %s",
            RUNTIME_NAME,
            RUNTIME_VERSION,
        )

        self._assert_constitution()

        self_check = (
            self.core_loader
            .self_check()
        )

        if not self_check.get("ok"):
            raise RuntimeError(
                "CORE-01 self-check failed"
            )

        validation = (
            self.validator
            .full_validation()
        )

        self._write_manifest()

        result = {
            "ok": validation.success,
            "runtime": RUNTIME_NAME,
            "runtime_version": (
                RUNTIME_VERSION
            ),
            "core_file": CORE_FILENAME,
            "core_self_check": (
                self_check
            ),
            "validation": {
                "success": (
                    validation.success
                ),
                "checks": (
                    validation.checks
                ),
                "errors": (
                    validation.errors
                ),
                "warnings": (
                    validation.warnings
                ),
            },
            "autonomous": True,
            "development_gateway": (
                self.gateway.healthy()
            ),
            "auto_dependencies": (
                AUTO_INSTALL_DEPENDENCIES
            ),
            "auto_git_commit": (
                AUTO_GIT_COMMIT
            ),
            "auto_deploy": (
                AUTO_DEPLOY
            ),
            "time": utc_now(),
        }

        self.db.event(
            "RUNTIME_BOOTSTRAP",
            (
                Risk.LOW
                if result["ok"]
                else Risk.HIGH
            ),
            result,
        )

        return result

    def health(self) -> Dict[str, Any]:
        self._assert_constitution()

        return (
            self.health_engine.check()
        )

    def develop(
        self,
        objective: str,
    ) -> Dict[str, Any]:
        self._assert_constitution()

        result = (
            self.developer.develop(
                objective
            )
        )

        self._assert_constitution()
        self._write_manifest()

        return {
            "ok": result.success,
            "checks": result.checks,
            "errors": result.errors,
            "warnings": result.warnings,
            "time": utc_now(),
        }

    def maintenance_once(
        self,
    ) -> Dict[str, Any]:
        self._assert_constitution()

        result = (
            self.maintenance
            .maintenance_cycle()
        )

        self._assert_constitution()
        self._write_manifest()

        return result

    def run_forever(self) -> int:
        bootstrap = self.bootstrap()

        if not bootstrap["ok"]:
            logger.warning(
                "Initial validation failed; "
                "runtime will attempt maintenance."
            )

        logger.info(
            "Autonomous runtime active. "
            "heartbeat=%ss maintenance=%ss",
            HEARTBEAT_SECONDS,
            MAINTENANCE_SECONDS,
        )

        last_maintenance = 0.0

        while not STOP_EVENT.is_set():
            try:
                self._assert_constitution()

                now = time.monotonic()

                if (
                    now - last_maintenance
                    >= MAINTENANCE_SECONDS
                ):
                    result = (
                        self.maintenance_once()
                    )

                    logger.info(
                        "Maintenance cycle: ok=%s",
                        result["ok"],
                    )

                    last_maintenance = now

                else:
                    health = self.health()

                    logger.info(
                        "Heartbeat: ok=%s",
                        health["ok"],
                    )

                STOP_EVENT.wait(
                    HEARTBEAT_SECONDS
                )

            except KeyboardInterrupt:
                STOP_EVENT.set()

            except Exception as exc:
                logger.error(
                    "Runtime cycle failure: %s\n%s",
                    SecretGuard.redact(
                        str(exc)
                    ),
                    SecretGuard.redact(
                        traceback.format_exc()
                    ),
                )

                self.db.event(
                    "RUNTIME_CYCLE_FAILURE",
                    Risk.HIGH,
                    {
                        "error": (
                            f"{type(exc).__name__}: "
                            f"{exc}"
                        )
                    },
                )

                STOP_EVENT.wait(
                    HEARTBEAT_SECONDS
                )

        logger.info(
            "Autonomous runtime stopped."
        )

        return 0


# ============================================================
# SIGNALS
# ============================================================

def handle_stop_signal(
    signum: int,
    frame: Any,
) -> None:
    del frame

    logger.info(
        "Stop signal received: %s",
        signum,
    )

    STOP_EVENT.set()


def install_signal_handlers() -> None:
    for sig in (
        signal.SIGINT,
        signal.SIGTERM,
    ):
        with contextlib.suppress(
            Exception
        ):
            signal.signal(
                sig,
                handle_stop_signal,
            )


# ============================================================
# STARTUP SELF-CHECK
# ============================================================

def runtime_self_check() -> Dict[str, Any]:
    checks: Dict[str, Any] = {
        "runtime_file": (
            RUNTIME_PATH.exists()
        ),
        "core_file": CORE_PATH.exists(),
        "directories": all(
            directory.exists()
            for directory in (
                DATA_DIR,
                LOG_DIR,
                STATE_DIR,
                BACKUP_DIR,
                STAGING_DIR,
                GENERATED_DIR,
                TEST_DIR,
            )
        ),
        "secret_redaction": False,
        "database": False,
        "core_import": False,
        "constitution": False,
    }

    test_secret = (
        "api_key=THIS_VALUE_MUST_HIDE"
    )

    checks["secret_redaction"] = (
        "THIS_VALUE_MUST_HIDE"
        not in SecretGuard.redact(
            test_secret
        )
    )

    try:
        db = RuntimeDatabase(
            RUNTIME_DB
        )

        with db.connect() as connection:
            connection.execute(
                "SELECT 1"
            ).fetchone()

        checks["database"] = True

    except Exception:
        checks["database"] = False

    try:
        loader = CoreLoader(
            CORE_PATH
        )

        loader.load()

        checks["core_import"] = True

        fingerprint = (
            loader
            .constitution_fingerprint()
        )

        checks["constitution"] = (
            len(fingerprint) == 64
        )

    except Exception:
        checks["core_import"] = False
        checks["constitution"] = False

    checks["ok"] = all(
        bool(value)
        for key, value in checks.items()
        if key != "ok"
    )

    return checks


# ============================================================
# CLI
# ============================================================

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog=RUNTIME_FILENAME,
        description=RUNTIME_NAME,
    )

    parser.add_argument(
        "--self-check",
        action="store_true",
        help=(
            "Run runtime self-check "
            "and exit."
        ),
    )

    parser.add_argument(
        "--health",
        action="store_true",
        help=(
            "Run full health check "
            "and exit."
        ),
    )

    parser.add_argument(
        "--bootstrap",
        action="store_true",
        help=(
            "Bootstrap runtime and exit."
        ),
    )

    parser.add_argument(
        "--maintenance-once",
        action="store_true",
        help=(
            "Run one autonomous "
            "maintenance cycle."
        ),
    )

    parser.add_argument(
        "--develop",
        metavar="OBJECTIVE",
        help=(
            "Request an autonomous "
            "development objective."
        ),
    )

    parser.add_argument(
        "--capabilities",
        action="store_true",
        help=(
            "Print discovered "
            "capabilities."
        ),
    )

    parser.add_argument(
        "--run",
        action="store_true",
        help=(
            "Run continuously."
        ),
    )

    return parser


# ============================================================
# MAIN
# ============================================================

def main() -> int:
    install_signal_handlers()

    parser = build_parser()
    args = parser.parse_args()

    try:
        if args.self_check:
            result = runtime_self_check()

            print(
                json.dumps(
                    result,
                    ensure_ascii=False,
                    indent=2,
                )
            )

            return (
                0
                if result["ok"]
                else 1
            )

        runtime = (
            MajdAutonomousRuntime()
        )

        if args.health:
            result = runtime.health()

            print(
                json.dumps(
                    result,
                    ensure_ascii=False,
                    indent=2,
                )
            )

            return (
                0
                if result["ok"]
                else 1
            )

        if args.bootstrap:
            result = runtime.bootstrap()

            print(
                json.dumps(
                    result,
                    ensure_ascii=False,
                    indent=2,
                )
            )

            return (
                0
                if result["ok"]
                else 1
            )

        if args.maintenance_once:
            result = (
                runtime
                .maintenance_once()
            )

            print(
                json.dumps(
                    result,
                    ensure_ascii=False,
                    indent=2,
                )
            )

            return (
                0
                if result["ok"]
                else 1
            )

        if args.develop:
            result = runtime.develop(
                args.develop
            )

            print(
                json.dumps(
                    result,
                    ensure_ascii=False,
                    indent=2,
                )
            )

            return (
                0
                if result["ok"]
                else 1
            )

        if args.capabilities:
            print(
                json.dumps(
                    CapabilityDiscovery
                    .discover(),
                    ensure_ascii=False,
                    indent=2,
                )
            )

            return 0

        # Default behavior is continuous autonomous operation.
        return runtime.run_forever()

    except KeyboardInterrupt:
        return 130

    except Exception as exc:
        logger.critical(
            "Fatal autonomous runtime error: %s\n%s",
            SecretGuard.redact(
                str(exc)
            ),
            SecretGuard.redact(
                traceback.format_exc()
            ),
        )

        return 1


if __name__ == "__main__":
    raise SystemExit(main())
